



DROP TABLE customer_purchases;
ALTER TABLE customer_purchases_usd
RENAME TO customer_purchases;
select * from customer_purchases ;

--Q1. What is the total revenue generated by male vs. female customers?
select gender , SUM(purchase_amount_usd)as revenue from customer_purchases 
group by gender;
select gender , sum(purchase_amount_usd)as revenue
from customer_purchases where gender = 'Male'
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id ,purchase_amount_usd
from customer_purchases where discount_applied  = 'Yes'
and purchase_amount_usd >=( select  AVG(purchase_amount_usd )FROM  customer_purchases) ;

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased  , round(avg( review_rating::numeric),2)as Avg_rating 
from customer_purchases group by  item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount_usd),2)from customer_purchases
where shipping_type in('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status , count(customer_id)as total_customers ,
round(avg(purchase_amount_usd),2)as avg_spend,
round(sum(purchase_amount_usd),2)as total_revenue
from customer_purchases group by subscription_status order by total_revenue , avg_spend desc;


--Q6. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
 select subscription_status , count (customer_id)as repeat_buyers
 from customer_purchases where previous_purchases >5
 group by subscription_status;


--Q7. What is the revenue contribution of each age group?
select age_group , sum(purchase_amount_usd)as total_revenue
from customer_purchases
group by age_group
order by total_revenue desc;





